const AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR";
const USER_NOT_FOUND = "USER_NOT_FOUND";
const NOT_AUTHORISED = "NOT_AUTHORISED";
const POST_NOT_FOUND = "POST_NOT_FOUND";
const COMMENT_NOT_FOUND = "COMMENT_NOT_FOUND";
const CHAT_NOT_FOUND = "CHAT_NOT_FOUND";